version: '3.9'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus/prometheus.yaml" ]
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/config.yaml:/etc/prometheus/prometheus.yaml

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3200:3200"
    volumes:
      - ./infra/tempo/config.yaml:/etc/tempo.yaml

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    volumes:
      - ./infra/otel-collector/config.yaml:/etc/otel-collector.yaml

  app:
    build:
      context: .
      target: dev
    image: house-staff:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    env_file: .env.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      otel-collector:
        condition: service_started
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    env_file: .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U andrii -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data: